### ISSUE TITLE
How to run it with docker

### ISSUE THREAD

**Issue by IIPoliII** [byceps/byceps#11]
Hello,

I saw there was a dockerfile I tried to use but sadly I can't make it to work.
Everything installs but when starting it doesn't start properly sadly.

Could you give me which config file I should change?

Thanks in advance!

**Comment by homeworkprod** [comment]
Hi, @IIPoliII!

What is the exact issue that you're facing?

**Comment by IIPoliII** [comment]
> Hi, @IIPoliII!
> 
> What is the exact issue that you're facing?

Thanks for your reply! Sorry that I didn't document it more! I'll come back tomorrow with a few more logs. thanks for the reply already

**Comment by homeworkprod** [comment]
I was able to take a look myself and figured that both the admin interface and the party site appear on ports 8081 and 8082, respectively, after:
- setting `SECRET_KEY` in `compose.yaml`
- `docker-compose up` (or `docker compose up`, depending on the Docker version)

**Comment by homeworkprod** [comment]
I have now properly documented how to run BYCEPS with Docker (Compose) at https://byceps.readthedocs.io/en/latest/installation_docker/index.html.

I even added a manually triggered action to execute the steps (except for actually start the services) in an isolated environment: https://github.com/byceps/byceps/actions/workflows/docker-test.yml

Along the way, I also changed secret key handling and added some missing demo data (but it still might be insufficient to demonstrate some use cases).

Closing this now as complete and due to lack of feedback.

Any feedback is still welcome; here in the issue tracker or on Discord. Thanks for checking out BYCEPS!
