### ISSUE TITLE
Use of `docker-compose` in documentation

### ISSUE THREAD

**Issue by The0mikkel** [byceps/byceps#15]
The current install/setup steps for docker, located in `docs/installation_docker/index.rst` references `docker-compose` as command, but Compose V2 deprecates this, with the build in `docker compose` command.

When following the install guide, I had to switch all the commands from `docker-compose` to `docker compose` manually to get the system running.

The official Compose V2 documentation calls for the move to `docker compose` from `docker-compose`: https://docs.docker.com/compose/migrate/

**Comment by Nissen96** [comment]
I had the same issue previously. The setup guide links directly to the official Docker and Docker Compose installation guides, but following these, you no longer install the standalone version (V1 - deprecated for two years and end-of-life since July 2023), but instead the Compose plugin (V2 - used since 2020).

New users (and hopefully most current) will therefore have `docker compose` and not `docker-compose` available - updating the setup guide to reflect this seems most sensible.

**Comment by homeworkprod** [comment]
Fixed in 588799155c2dd653083b8a9ed5c682ae18b1e70e. Thank you!
